version: '3'
services:
  bidwire:
    build: .
    volumes:
     - .:/bidwire
    depends_on:
     - database
    entrypoint: ./wait-for-it.sh database:5432 --
    command: ./setup.sh
    environment:
    # Full Postgres connection string, including user@host/db_name
    - POSTGRES_ENDPOINT=postgresql://postgres@database/postgres

  database:
    image: postgres:9.6
    ports:
    - "5432:5432"
